kind: pipeline
name: default

steps:
  - name: master
    image: alpine/git
    pull: false
    commands:
      - git checkout origin/master -B master
    when:
      branch:
        - master

  - name: docker-master
    image: plugins/docker
    pull: false
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      repo: registry.cn-heyuan.aliyuncs.com/omar-docker/drone
      registry: registry.cn-heyuan.aliyuncs.com
      dockerfile: Dockerfile
      username:
        from_secret: 17778696367
      password:
        from_secret: t5475949597
    when:
      branch:
        - master

  - name: ssh-master
    image: appleboy/drone-ssh
    pull: false
    settings:
      host:
        - 43.143.109.42
      username: root
      ssh_key:
        from_secret: ssh_key
      script:
        - /data/drone/run.sh
    when:
      branch:
        - master

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - master